# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: uber.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'uber.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuber.proto\x12\x04uber\"\x07\n\x05Vacio\"V\n\x14TerminarViajeRequest\x12 \n\x08posicion\x18\x01 \x01(\x0b\x32\x0e.uber.Posicion\x12\r\n\x05\x63osto\x18\x02 \x01(\x01\x12\r\n\x05placa\x18\x03 \x01(\t\" \n\x08Posicion\x12\t\n\x01X\x18\x01 \x01(\x02\x12\t\n\x01Y\x18\x02 \x01(\x02\"n\n\x08infoAuto\x12\x16\n\x0e\x64isponibilidad\x18\x01 \x01(\x08\x12\x1d\n\x05posXY\x18\x02 \x01(\x0b\x32\x0e.uber.Posicion\x12\x1c\n\x04tipo\x18\x03 \x01(\x0e\x32\x0e.uber.tipoUber\x12\r\n\x05placa\x18\x04 \x01(\t\"E\n\x0cinfoServicio\x12\x0e\n\x06viajes\x18\x01 \x01(\x05\x12\x13\n\x0b\x61utosLibres\x18\x02 \x01(\x05\x12\x10\n\x08ganancia\x18\x03 \x01(\x02*8\n\x08tipoUber\x12\x0f\n\x0bUBER_PLANET\x10\x00\x12\x0b\n\x07UBER_XL\x10\x01\x12\x0e\n\nUBER_BLACK\x10\x02\x32\xab\x01\n\x04Uber\x12\x32\n\x0esolicitarViaje\x12\x0e.uber.Posicion\x1a\x0e.uber.infoAuto\"\x00\x12:\n\rterminarViaje\x12\x1a.uber.TerminarViajeRequest\x1a\x0b.uber.Vacio\"\x00\x12\x33\n\x0e\x65stadoServicio\x12\x0b.uber.Vacio\x1a\x12.uber.infoServicio\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'uber_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TIPOUBER']._serialized_start=334
  _globals['_TIPOUBER']._serialized_end=390
  _globals['_VACIO']._serialized_start=20
  _globals['_VACIO']._serialized_end=27
  _globals['_TERMINARVIAJEREQUEST']._serialized_start=29
  _globals['_TERMINARVIAJEREQUEST']._serialized_end=115
  _globals['_POSICION']._serialized_start=117
  _globals['_POSICION']._serialized_end=149
  _globals['_INFOAUTO']._serialized_start=151
  _globals['_INFOAUTO']._serialized_end=261
  _globals['_INFOSERVICIO']._serialized_start=263
  _globals['_INFOSERVICIO']._serialized_end=332
  _globals['_UBER']._serialized_start=393
  _globals['_UBER']._serialized_end=564
# @@protoc_insertion_point(module_scope)
