# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import disparos_pb2 as disparos__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in disparos_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DisparoStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.dimeCentroDianna = channel.unary_unary(
                '/disparos.Disparo/dimeCentroDianna',
                request_serializer=disparos__pb2.Vacio.SerializeToString,
                response_deserializer=disparos__pb2.Distancia.FromString,
                _registered_method=True)
        self.dispararCannon = channel.unary_unary(
                '/disparos.Disparo/dispararCannon',
                request_serializer=disparos__pb2.InfoDisparo.SerializeToString,
                response_deserializer=disparos__pb2.Distancia.FromString,
                _registered_method=True)
        self.mejorDisparo = channel.unary_unary(
                '/disparos.Disparo/mejorDisparo',
                request_serializer=disparos__pb2.Vacio.SerializeToString,
                response_deserializer=disparos__pb2.Usuario.FromString,
                _registered_method=True)


class DisparoServicer(object):
    """Missing associated documentation comment in .proto file."""

    def dimeCentroDianna(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def dispararCannon(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def mejorDisparo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DisparoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'dimeCentroDianna': grpc.unary_unary_rpc_method_handler(
                    servicer.dimeCentroDianna,
                    request_deserializer=disparos__pb2.Vacio.FromString,
                    response_serializer=disparos__pb2.Distancia.SerializeToString,
            ),
            'dispararCannon': grpc.unary_unary_rpc_method_handler(
                    servicer.dispararCannon,
                    request_deserializer=disparos__pb2.InfoDisparo.FromString,
                    response_serializer=disparos__pb2.Distancia.SerializeToString,
            ),
            'mejorDisparo': grpc.unary_unary_rpc_method_handler(
                    servicer.mejorDisparo,
                    request_deserializer=disparos__pb2.Vacio.FromString,
                    response_serializer=disparos__pb2.Usuario.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'disparos.Disparo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('disparos.Disparo', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Disparo(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def dimeCentroDianna(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/disparos.Disparo/dimeCentroDianna',
            disparos__pb2.Vacio.SerializeToString,
            disparos__pb2.Distancia.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def dispararCannon(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/disparos.Disparo/dispararCannon',
            disparos__pb2.InfoDisparo.SerializeToString,
            disparos__pb2.Distancia.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def mejorDisparo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/disparos.Disparo/mejorDisparo',
            disparos__pb2.Vacio.SerializeToString,
            disparos__pb2.Usuario.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
