# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fechas.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'fechas.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x66\x65\x63has.proto\x12\x06\x66\x65\x63has\"/\n\x05\x46\x65\x63ha\x12\x0b\n\x03\x64ia\x18\x01 \x01(\x05\x12\x0b\n\x03mes\x18\x02 \x01(\x05\x12\x0c\n\x04\x61nio\x18\x03 \x01(\x05\"?\n\x0f\x46\x65\x63haNumeroDias\x12\x1c\n\x05\x66\x65\x63ha\x18\x04 \x01(\x0b\x32\r.fechas.Fecha\x12\x0e\n\x06numero\x18\x05 \x01(\x05\x32u\n\x06\x46\x65\x63has\x12\x30\n\x0esiguienteFecha\x12\r.fechas.Fecha\x1a\r.fechas.Fecha\"\x00\x12\x39\n\rsumaDiasFecha\x12\x17.fechas.FechaNumeroDias\x1a\r.fechas.Fecha\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fechas_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FECHA']._serialized_start=24
  _globals['_FECHA']._serialized_end=71
  _globals['_FECHANUMERODIAS']._serialized_start=73
  _globals['_FECHANUMERODIAS']._serialized_end=136
  _globals['_FECHAS']._serialized_start=138
  _globals['_FECHAS']._serialized_end=255
# @@protoc_insertion_point(module_scope)
