/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "uber.h"

bool_t
xdr_tipo_uber (XDR *xdrs, tipo_uber *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_posicion (XDR *xdrs, posicion *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->y))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_info_auto (XDR *xdrs, info_auto *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_bool (xdrs, &objp->disponibilidad))
		 return FALSE;
	 if (!xdr_posicion (xdrs, &objp->posXY))
		 return FALSE;
	 if (!xdr_tipo_uber (xdrs, &objp->tipo))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->placa, 7,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_info_servicio (XDR *xdrs, info_servicio *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->viajes))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->autos_libres))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->ganancia))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_terminar_viaje_1_argument (XDR *xdrs, terminar_viaje_1_argument *objp)
{
	 if (!xdr_posicion (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->arg3, ~0))
		 return FALSE;
	return TRUE;
}
