/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _UBER_H_RPCGEN
#define _UBER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


enum tipo_uber {
	UBER_PLANET = 0,
	UBER_XL = 1,
	UBER_BLACK = 2,
};
typedef enum tipo_uber tipo_uber;

struct posicion {
	double x;
	double y;
};
typedef struct posicion posicion;

struct info_auto {
	bool_t disponibilidad;
	posicion posXY;
	tipo_uber tipo;
	char placa[7];
};
typedef struct info_auto info_auto;

struct info_servicio {
	int viajes;
	int autos_libres;
	double ganancia;
};
typedef struct info_servicio info_servicio;

struct terminar_viaje_1_argument {
	posicion arg1;
	double arg2;
	char *arg3;
};
typedef struct terminar_viaje_1_argument terminar_viaje_1_argument;

#define UBER 0x20000002
#define UBER_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define solicitar_viaje 1
extern  info_auto * solicitar_viaje_1(posicion , CLIENT *);
extern  info_auto * solicitar_viaje_1_svc(posicion , struct svc_req *);
#define terminar_viaje 2
extern  void * terminar_viaje_1(posicion , double , char *, CLIENT *);
extern  void * terminar_viaje_1_svc(posicion , double , char *, struct svc_req *);
#define estado_servicio 3
extern  info_servicio * estado_servicio_1(CLIENT *);
extern  info_servicio * estado_servicio_1_svc(struct svc_req *);
extern int uber_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define solicitar_viaje 1
extern  info_auto * solicitar_viaje_1();
extern  info_auto * solicitar_viaje_1_svc();
#define terminar_viaje 2
extern  void * terminar_viaje_1();
extern  void * terminar_viaje_1_svc();
#define estado_servicio 3
extern  info_servicio * estado_servicio_1();
extern  info_servicio * estado_servicio_1_svc();
extern int uber_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_tipo_uber (XDR *, tipo_uber*);
extern  bool_t xdr_posicion (XDR *, posicion*);
extern  bool_t xdr_info_auto (XDR *, info_auto*);
extern  bool_t xdr_info_servicio (XDR *, info_servicio*);
extern  bool_t xdr_terminar_viaje_1_argument (XDR *, terminar_viaje_1_argument*);

#else /* K&R C */
extern bool_t xdr_tipo_uber ();
extern bool_t xdr_posicion ();
extern bool_t xdr_info_auto ();
extern bool_t xdr_info_servicio ();
extern bool_t xdr_terminar_viaje_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_UBER_H_RPCGEN */
