/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "uber.h"


void
uber_1(char *host)
{
	CLIENT *clnt;
	void  *result_1;
	info_auto  *result_2;
	posicion solicitar_viaje_1_arg1;
	void  *result_3;
	posicion terminar_viaje_1_arg1;
	double terminar_viaje_1_arg2;
	char *terminar_viaje_1_arg3;
	info_servicio  *result_4;

#ifndef	DEBUG
	clnt = clnt_create (host, UBER, UBER_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = init_1(clnt);
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = solicitar_viaje_1(solicitar_viaje_1_arg1, clnt);
	if (result_2 == (info_auto *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = terminar_viaje_1(terminar_viaje_1_arg1, terminar_viaje_1_arg2, terminar_viaje_1_arg3, clnt);
	if (result_3 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = estado_servicio_1(clnt);
	if (result_4 == (info_servicio *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	uber_1 (host);
exit (0);
}
