/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdio.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <math.h>
#include "uber.h"

#define NUM_AUTOS 8

static int viajes = 0;
static double ganancia = 0;

static info_auto vehiculos[NUM_AUTOS];
static bool inicializado = false;

void generar_placa(char *cadena)
{
	for (int i = 0; i < 3; i++)
	{
		cadena[i] = '0' + rand() % 10;
	}

	for (int i = 3; i < 6; i++)
	{
		cadena[i] = 'A' + rand() % 26;
	}

	cadena[6] = '\0';
}

void init_autos(void)
{
	info_auto auto_info;
	char cadena[6];
	srand(time(NULL));

	// Generar autos aleatorios
	for (int i = 0; i < NUM_AUTOS; i++)
	{
		generar_placa(cadena);
		auto_info.disponibilidad = true;
		auto_info.posXY.x = rand() % 50;
		auto_info.posXY.y = rand() % 50;
		auto_info.tipo = rand() % 3;
		strcpy(auto_info.placa, cadena);
		vehiculos[i] = auto_info;
	}
}

info_auto *
solicitar_viaje_1_svc(posicion posicion_pasajero, struct svc_req *rqstp)
{
	static info_auto auto_info;

	double distancia_min = INFINITY;
	double distancia = 0;
	int indice = -1;

	for (int i = 0; i < NUM_AUTOS; i++)
	{
		if (vehiculos[i].disponibilidad)
		{
			distancia = sqrt(pow(posicion_pasajero.x - vehiculos[i].posXY.x, 2) 
				+ pow(posicion_pasajero.y - vehiculos[i].posXY.y, 2));

			if(distancia < distancia_min) {
				distancia_min = distancia;
				indice = i;
			}
		}
	}
	if (indice == -1) {
		printf("No hay autos");
		return NULL;
	} else {
		vehiculos[indice].disponibilidad = false;
		return &vehiculos[indice];
	}
}

void *
terminar_viaje_1_svc(posicion posicion_final, double costo, char *placas, struct svc_req *rqstp)
{
	// Busca el auto en el arreglo con la placa
	for (int i = 0; i < NUM_AUTOS; i++)
	{
		if (strcmp(placas, vehiculos[i].placa) == 0)
		{
			// Cambia a disponible
			vehiculos[i].disponibilidad = true;

			// Cambia la posición del auto a la del cliente
			vehiculos[i].posXY = posicion_final;

			// Suma el costo a la ganancia
			ganancia += costo;

			// Aumenta el número de viajes
			viajes++;

			printf("Auto con placas: %s está disponible\n", placas);
		}
	}
	return NULL;
}

info_servicio *
estado_servicio_1_svc(struct svc_req *rqstp)
{
	if (!inicializado)
	{
		init_autos();
		inicializado = true;
		printf("\nServidor inicializado.\n");
	}

	// Inicializa estructura
	static info_servicio estado;

	estado.autos_libres = 0;

	// Almacena el número de viajes realizados al momento
	estado.viajes = viajes;

	// Almacena la ganancia total al momento
	estado.ganancia = ganancia;

	// Cuenta los autos disponibles y los almacena

	for (int i = 0; i < NUM_AUTOS; i++)
	{
		if (vehiculos[i].disponibilidad)
		{
			estado.autos_libres++;
		}
	}

	return &estado;
}
